name: 60min - DST

on:
  schedule:
    - cron: "*/60 * * * *"  # Se ejecuta cada 60 minutos
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  run_script:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verificar Python en el sistema
        run: |
          where python
          python --version

      - name: Instalar dependencias
        run: python -m pip install -r requirements_Grupo_2.txt || echo "No hay dependencias que instalar"


      - name: Ejecutar script
        run: python DST_PLOT_SWP_GRUPO_2.py

      - name: Commit y push si hay cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 1. Confirma (commit) los cambios que haya generado el script
          git add .
          git commit -m "Auto-commit de cambios generados antes del rebase" || echo "No hay cambios pendientes"
      
          # 2. Hacer pull --rebase con el repositorio remoto
          git pull --rebase https://x-access-token:${GITHUB_TOKEN}@github.com/SpaceWeatherPeru/Scripts_SWP.git main
      
          # 3. Añadir y commitear de nuevo si tu script generó cambios adicionales tras el pull
          git add .
          git commit -m "Subiendo imagen generada automáticamente" || echo "No hay cambios para commitear"
      
          # 4. Empujar al remoto
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/SpaceWeatherPeru/Scripts_SWP.git HEAD:main

