name: 10min - GLM

on:
  schedule:
    - cron: "*/10 * * * *"  # Se ejecuta cada 10 minutos
  #workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt || echo "No hay dependencias que instalar"

      - name: Ejecutar script
        run: python PLOT_GLM_INPE_PLOT_SWP_GRUPO_3.py

      - name: Commit y push si hay cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 1. Actualizar el repositorio local con los últimos cambios
          git pull --rebase https://x-access-token:${GITHUB_TOKEN}@github.com/SpaceWeatherPeru/Scripts_SWP.git main
      
          # 2. Añadir y hacer commit de cambios locales
          git add .
          git commit -m "Subiendo imagen generada automáticamente" || echo "No hay cambios para commitear"
      
          # 3. Empujar
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/SpaceWeatherPeru/Scripts_SWP.git HEAD:main
